/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype;

import javax.swing.JOptionPane;
import szakdoga_prototype.gameengine.GameCore;
import szakdoga_prototype.gameengine.exceptions.GameSettingsInvalidException;
import szakdoga_prototype.gameengine.exceptions.GameSetupIncompleteException;
import szakdoga_prototype.gameengine.exceptions.PlayerAlreadyRegisteredException;
import szakdoga_prototype.gameengine.exceptions.PlayerListFullException;
import szakdoga_prototype.nimgame.core.NimGameCore;
import szakdoga_prototype.nimgame.northcott.NorthcottMainPanel;
import szakdoga_prototype.nimgame.original.UI.NimMainPanel;
import szakdoga_prototype.providers.GameEntityProvider;

/**
 *
 * @author matthew
 */
public class MainWindow extends javax.swing.JFrame {

    public static enum SupportedGames {
        GAME_NIM,
        GAME_NORTHCOTT
    }

    private GameController gameController;

    private void createGame(SupportedGames gameToCreate) {
        GameEntityProvider gameEntityProvider;
        GameCore game;
        if (this.gameController != null) {
            this.gameController.destroyGame();
        }
        switch (gameToCreate) {
            case GAME_NIM: {
                game = new NimGameCore();
                gameEntityProvider = new NimMainPanel((NimGameCore) game);
                break;
            }
            case GAME_NORTHCOTT: {
                JOptionPane.showMessageDialog(this, "The selected game type is not yet implemented.");
                game = new NimGameCore();
                gameEntityProvider = new NorthcottMainPanel();
                break;
            }
            default: {
                JOptionPane.showMessageDialog(this, "The selected game type is not yet implemented.");
                return;
            }
        }
        this.gameController = new GameController(game, gameEntityProvider);
        gameController.loadUIElements(gameMainPluginPlaceholder, gameSettingsPluginplaceholder, gameStatusPanelPluginPlaceholder);
        startGameButton.setEnabled(true);
        this.repaint();
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameMainPluginPlaceholder = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        startGameButton = new javax.swing.JButton();
        gameSettingsPanel = new javax.swing.JPanel();
        gameSettingsPluginplaceholder = new javax.swing.JPanel();
        gameStatusPanelPluginPlaceholder = new javax.swing.JPanel();
        gameSettingsLabel = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        miSelectGameNim = new javax.swing.JRadioButtonMenuItem();
        miSelectGameChess = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NimGame");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));

        gameMainPluginPlaceholder.setLayout(new javax.swing.BoxLayout(gameMainPluginPlaceholder, javax.swing.BoxLayout.LINE_AXIS));

        sidePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sidePanel.setPreferredSize(new java.awt.Dimension(300, 739));

        startGameButton.setText("Start Game");
        startGameButton.setEnabled(false);
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        gameSettingsPluginplaceholder.setLayout(new javax.swing.BoxLayout(gameSettingsPluginplaceholder, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout gameSettingsPanelLayout = new javax.swing.GroupLayout(gameSettingsPanel);
        gameSettingsPanel.setLayout(gameSettingsPanelLayout);
        gameSettingsPanelLayout.setHorizontalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSettingsPluginplaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gameSettingsPanelLayout.setVerticalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(gameSettingsPluginplaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gameStatusPanelPluginPlaceholder.setLayout(new javax.swing.BoxLayout(gameStatusPanelPluginPlaceholder, javax.swing.BoxLayout.LINE_AXIS));

        gameSettingsLabel.setText("Game settings:");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameStatusPanelPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameSettingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(gameSettingsLabel)
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameStatusPanelPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startGameButton))
        );

        jMenu1.setText("Program");

        jMenu3.setText("Select game");

        miSelectGameNim.setSelected(true);
        miSelectGameNim.setText("Classic NIM game");
        miSelectGameNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSelectGameNimActionPerformed(evt);
            }
        });
        jMenu3.add(miSelectGameNim);

        miSelectGameChess.setText("NIM Chess");
        miSelectGameChess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSelectGameChessActionPerformed(evt);
            }
        });
        jMenu3.add(miSelectGameChess);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Reset program");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mainMenu.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenu.add(jMenu2);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameMainPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameMainPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        try {
            gameController.startGame();
            startGameButton.setEnabled(false);
            gameSettingsPanel.setEnabled(false);
        } catch (GameSetupIncompleteException ex) {
            JOptionPane.showMessageDialog(this, "Game setup is incomplete: " + ex.getMessage());
        } catch (GameSettingsInvalidException | PlayerAlreadyRegisteredException | PlayerListFullException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (this.gameController != null) {
            gameController.destroyGame();
            this.gameController = null;
            startGameButton.setEnabled(false);
            this.revalidate();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miSelectGameNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSelectGameNimActionPerformed
        createGame(SupportedGames.GAME_NIM);
    }//GEN-LAST:event_miSelectGameNimActionPerformed

    private void miSelectGameChessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSelectGameChessActionPerformed
        createGame(SupportedGames.GAME_NORTHCOTT);
    }//GEN-LAST:event_miSelectGameChessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameMainPluginPlaceholder;
    private javax.swing.JLabel gameSettingsLabel;
    private javax.swing.JPanel gameSettingsPanel;
    private javax.swing.JPanel gameSettingsPluginplaceholder;
    private javax.swing.JPanel gameStatusPanelPluginPlaceholder;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JRadioButtonMenuItem miSelectGameChess;
    private javax.swing.JRadioButtonMenuItem miSelectGameNim;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
