/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import szakdoga_prototype.gameengine.GameCore;
import szakdoga_prototype.gameengine.exceptions.GameSettingsInvalidException;
import szakdoga_prototype.gameengine.exceptions.GameSetupIncompleteException;
import szakdoga_prototype.gameengine.exceptions.PlayerAlreadyRegisteredException;
import szakdoga_prototype.gameengine.exceptions.PlayerListFullException;
import szakdoga_prototype.nimgame.core.NimGameCore;
import szakdoga_prototype.nimgame.original.UI.NimMainPanel;
import szakdoga_prototype.nimgame.original.UI.NimSettingsPanel;

/**
 *
 * @author matthew
 */
public class MainWindow extends javax.swing.JFrame {
    public static enum SupportedGames {
        GAME_NIM
    }

    private GameElements gameElements;

    private void loadGame(SupportedGames gameToLoad) {
        JPanel gameSettingsPlugin = null, gameMainPlugin = null;
        GameCore game = null;
        if (this.gameElements != null) {
            this.gameElements.destroyGame();
        }
        switch (gameToLoad) {
            case GAME_NIM: {
                game = new NimGameCore();
                gameSettingsPlugin = new NimSettingsPanel();
                gameMainPlugin = new NimMainPanel((NimGameCore) game, gameInfoPanel);
                break;
            }
        }
        this.gameElements = new GameElements(game, (GameSettingsProvider) gameSettingsPlugin, gameSettingsPlugin, gameMainPlugin);
        gameSettingsPluginplaceholder.add(gameSettingsPlugin);
        gameSettingsPluginplaceholder.validate();
        gameMainPluginPlaceholder.add(gameMainPlugin);
        gameMainPluginPlaceholder.validate();
        gameSettingsPanel.setEnabled(true);
        startGameButton.setEnabled(true);
        this.repaint();
    }


    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameMainPluginPlaceholder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        startGameButton = new javax.swing.JButton();
        gameInfoPanel = new szakdoga_prototype.GameInfoPanel();
        gameSettingsPanel = new javax.swing.JPanel();
        gameSettingsLabel = new javax.swing.JLabel();
        gameSettingsPluginplaceholder = new javax.swing.JPanel();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        miSelectGameNim = new javax.swing.JRadioButtonMenuItem();
        miSelectGameChess = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NimGame");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        gameMainPluginPlaceholder.setLayout(new javax.swing.BoxLayout(gameMainPluginPlaceholder, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 739));

        startGameButton.setText("Start Game");
        startGameButton.setEnabled(false);
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        gameSettingsLabel.setText("Game settings:");

        gameSettingsPluginplaceholder.setLayout(new javax.swing.BoxLayout(gameSettingsPluginplaceholder, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout gameSettingsPanelLayout = new javax.swing.GroupLayout(gameSettingsPanel);
        gameSettingsPanel.setLayout(gameSettingsPanelLayout);
        gameSettingsPanelLayout.setHorizontalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameSettingsPluginplaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                        .addComponent(gameSettingsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gameSettingsPanelLayout.setVerticalGroup(
            gameSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameSettingsPluginplaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addComponent(gameSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startGameButton)
                .addContainerGap())
        );

        jMenu1.setText("Program");

        jMenu3.setText("Select game");

        miSelectGameNim.setSelected(true);
        miSelectGameNim.setText("Classic NIM game");
        miSelectGameNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSelectGameNimActionPerformed(evt);
            }
        });
        jMenu3.add(miSelectGameNim);

        miSelectGameChess.setText("NIM Chess");
        jMenu3.add(miSelectGameChess);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Reset program");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mainMenu.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenu.add(jMenu2);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameMainPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameMainPluginPlaceholder, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        try {
            gameElements.getGame().loadGameSettings(gameElements.getSettingsProvider().getGameSettings());
            gameElements.getGame().startGame();
            startGameButton.setEnabled(false);
            gameSettingsPanel.setEnabled(false);
        } catch (GameSetupIncompleteException ex) {
            JOptionPane.showMessageDialog(this, "Game setup is incomplete: " + ex.getMessage());
        } catch (GameSettingsInvalidException | PlayerAlreadyRegisteredException | PlayerListFullException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (this.gameElements != null) {
            gameElements.destroyGame();
            this.gameElements = null;
            startGameButton.setEnabled(false);
            this.revalidate();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miSelectGameNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSelectGameNimActionPerformed
        loadGame(SupportedGames.GAME_NIM);
    }//GEN-LAST:event_miSelectGameNimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private szakdoga_prototype.GameInfoPanel gameInfoPanel;
    private javax.swing.JPanel gameMainPluginPlaceholder;
    private javax.swing.JLabel gameSettingsLabel;
    private javax.swing.JPanel gameSettingsPanel;
    private javax.swing.JPanel gameSettingsPluginplaceholder;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JRadioButtonMenuItem miSelectGameChess;
    private javax.swing.JRadioButtonMenuItem miSelectGameNim;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
