/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameplayer.nimgame.northcott.UI;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author matthew
 */
public class ChessField extends javax.swing.JPanel {

    private final int fieldId;
    private final int columnId;
    private final Color backgroundColor;
    private final ChessColumn parent;
    private boolean hidden = false;

    /**
     * Creates new form ChessField
     */
    public ChessField(int fieldId, int columnId, ChessColumn parent) {
        this.parent = parent;
        this.fieldId = fieldId;
        this.columnId = columnId;
        initComponents();
        this.backgroundColor = ((fieldId + columnId) % 2 == 0) ? BACKGROUND_COLOR : BACKGROUND_ALTERNMATE_COLOR;
        setBackground(this.backgroundColor);
    }

    public static Color BACKGROUND_COLOR = new Color(209, 139, 71);
    public static Color BACKGROUND_ALTERNMATE_COLOR = new Color(255, 206, 158);
    public static Color HIDDEN_COLOR = new Color(0, 0, 0);

    public void setHidden(boolean isHidden) {
        this.hidden = isHidden;
        if (isHidden) {
            this.setBackground(HIDDEN_COLOR);
        } else {
            this.setBackground(this.backgroundColor);
        }
    }

    public void setPawnVisible(Component pawnComponent) {
        if (pawnComponent != null) {
            this.add(pawnComponent);
        } else {
            this.removeAll();
        }
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        parent.fieldClicked(this);
    }//GEN-LAST:event_formMouseClicked

    public int getFieldId() {
        return fieldId;
    }

    public int getColumnId() {
        return columnId;
    }

    public boolean isHidden() {
        return hidden;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
