/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype.nimgame.northcott.UI;

import javax.swing.JLabel;

/**
 *
 * @author matthew
 */
public class ChessSideColumn extends javax.swing.JPanel {

    private int rowCount;

    /**
     * Creates new form ChessSideCulomn
     */
    public ChessSideColumn(int rowCount) {
        initComponents();
        for (int i = 0; i < rowCount; i++) {
            this.add(new JLabel(Integer.toString(i + 1)));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
