/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype.nimgame.northcott.UI;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author matthew
 */
public class ChessField extends javax.swing.JPanel {

    private final int fieldId;
    private final int columnId;
    private final Color backgroundColor;

    /**
     * Creates new form ChessField
     */
    public ChessField(int fieldId, int columnId) {
        this.fieldId = fieldId;
        this.columnId = columnId;
        initComponents();
        this.backgroundColor = ((fieldId + columnId) % 2 == 0) ? BACKGROUND_COLOR : BACKGROUND_ALTERNMATE_COLOR;
        setBackground(this.backgroundColor);
        this.add(new JLabel(fieldId + "," + columnId));
    }

    public static Color BACKGROUND_COLOR = new Color(209, 139, 71);
    public static Color BACKGROUND_ALTERNMATE_COLOR = new Color(255, 206, 158);
    public static Color HIDDEN_COLOR = new Color(0, 0, 0);

    public void setHidden(boolean isHidden) {
        if (isHidden) {
            this.setBackground(HIDDEN_COLOR);
        } else {
            this.setBackground(this.backgroundColor);
        }
    }

    public void displayPawn(boolean pawnVisible) {
        this.removeAll();
        if (pawnVisible) {
            this.add(new JLabel("PAWN"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
