/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype.nimgame.northcott.UI;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author matthew
 */
public class ChessColumn extends javax.swing.JPanel {

    private final int heapID;
    private int heapMaxSize;
    private List<ChessField> fields;


    private void createFields(){
        fieldContainer.removeAll();
        fields = new ArrayList<>(heapMaxSize);
        for (int i = 0; i < heapMaxSize; i++) {
            fields.add(new ChessField(heapID, i));
            fieldContainer.add(fields.get(i));
        }
        
    }

    public ChessColumn(int heapID, int heapMaxSize) {
        this.heapID = heapID;
        this.heapMaxSize = heapMaxSize;
        initComponents();
        createFields();
    }

    public void activateTopPlayer() {

    }

    public void activateBottomPlayer() {

    }
    
    public void chessDimensionChanged(int fieldCount){
        this.heapMaxSize=fieldCount;
        createFields();
    }

    /**
     * Creates new form ChessColumn
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPawnPosition = new javax.swing.JSpinner();
        bottomPawnPosition = new javax.swing.JSpinner();
        fieldContainer = new javax.swing.JPanel();

        fieldContainer.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPawnPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(bottomPawnPosition)
            .addComponent(fieldContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPawnPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPawnPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bottomPawnPosition;
    private javax.swing.JPanel fieldContainer;
    private javax.swing.JSpinner topPawnPosition;
    // End of variables declaration//GEN-END:variables
}
