/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameplayer.nimgame.standard.UI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import gameplayer.gameengine.eventmanager.EventChannel;
import gameplayer.gameengine.eventmanager.EventChannelInvalidException;
import gameplayer.gameengine.eventmanager.EventManager;
import gameplayer.gameengine.events.GameEvent;
import gameplayer.nimgame.standard.NimPlayerSettings;

/**
 *
 * @author Máté Pozsgay
 */
public class PlayerEntryPanel extends javax.swing.JPanel {

    private ButtonGroup starterGroup = new ButtonGroup();
    private int playerID;
    private EventChannel eventChannel;

    /**
     * Creates new form PlayerEntryPanel
     */
    public PlayerEntryPanel() { // Dummy function for Netbeans GUI editor
        initComponents();
    }

    public PlayerEntryPanel(int playerID, ButtonGroup starterGroup){
        this.starterGroup = starterGroup;
        this.playerID = playerID;
        try {
            this.eventChannel = EventManager.getEventChannel(EventManager.EVENT_REGISTRY.EVENT_UI_SETTINGS);
        } catch (EventChannelInvalidException ex) {
            Logger.getLogger(PlayerEntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        starterRadioButton = new javax.swing.JRadioButton();
        playerNameTextfield = new javax.swing.JTextField();
        isAICheckBox = new javax.swing.JCheckBox();

        starterGroup.add(starterRadioButton);

        playerNameTextfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        isAICheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAICheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(starterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameTextfield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isAICheckBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(isAICheckBox)
                        .addComponent(playerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(starterRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isAICheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAICheckBoxActionPerformed
        eventChannel.dispatchEvent(new GameEvent(this));
    }//GEN-LAST:event_isAICheckBoxActionPerformed

    public void setStarter(boolean selected) {
        starterRadioButton.setSelected(selected);
    }

    public boolean isStarter() {
        return starterRadioButton.isSelected();
    }

    public String getPlayerName() {
        return playerNameTextfield.getText();
    }

    public int getPlayerID() {
        return playerID;
    }

    public boolean isAI() {
        return isAICheckBox.isSelected();
    }

    public NimPlayerSettings getPlayerSettings(){
        return new NimPlayerSettings(playerID, getPlayerName(), isAI(), isStarter());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isAICheckBox;
    private javax.swing.JTextField playerNameTextfield;
    private javax.swing.JRadioButton starterRadioButton;
    // End of variables declaration//GEN-END:variables
}
