/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szakdoga_prototype.nimgame.original.UI;

import javax.swing.ButtonGroup;

/**
 *
 * @author matthew
 */
public class PlayerEntryPanel extends javax.swing.JPanel {

    ButtonGroup starterGroup = new ButtonGroup();

    /**
     * Creates new form PlayerEntryPanel
     */
    
    
    public PlayerEntryPanel(ButtonGroup starterGroup) {
        this.starterGroup = starterGroup;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        starterRadioButton = new javax.swing.JRadioButton();
        playerNameTextfield = new javax.swing.JTextField();
        isAICheckBox = new javax.swing.JCheckBox();

        starterGroup.add(starterRadioButton);

        playerNameTextfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(starterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerNameTextfield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isAICheckBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(isAICheckBox)
                        .addComponent(playerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(starterRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setStarter(boolean selected) {
        starterRadioButton.setSelected(selected);
    }

    public boolean isStarter() {
        return starterRadioButton.isSelected();
    }

    public String getPlayerName() {
        return playerNameTextfield.getText();
    }

    public boolean isAI() {
        return isAICheckBox.isSelected();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isAICheckBox;
    private javax.swing.JTextField playerNameTextfield;
    private javax.swing.JRadioButton starterRadioButton;
    // End of variables declaration//GEN-END:variables
}
